name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-publish:
    uses: Kevin-Dohmen/pipelines-generic/presets/dotnet/libraries.yml@main
    with:
      solutionPath: 'src/MyLibrary.sln'
      skipTests: true
    