name: Publish as Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-publish:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[run-ci]')
    uses: Kevin-Dohmen-Projects/pipelines-generic/.github/workflows/dotnet-libraries.yml@main
    with:
      solutionPath: "CSharp_ASCII_Render_Engine.sln"
  