name: Publish

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[run-ci]')
    uses: Kevin-Dohmen-Projects-Automation/workflows-generic/.github/workflows/dotnet-generic.yml@main
    with:
      solutionPath: "ASCII_Render_Engine/CSharp_ASCII_Render_Engine.sln"
      csprojPath: "ASCII_Render_Engine/ASCII_Render_Engine.csproj"
      publish-package: true
      publish-release: true
